name: Bangle Bug report
description: "Bangle: Create a issue to help us improve!"
title: "Please give it a short description and provide the affected app/widget."
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ** If you have a question then ask it at the [bangle forum](http://forum.espruino.com/microcosms/1424/), please! **
  - type: dropdown
    id: hwversion
    attributes:
      label: Affected hardware version
      description: |
        Which Bangle hardware version(s) is/are affected?
        Hint: You can select both with ctrl key.
      options:
        - label: Bangle 1
        - label: Bangle 2
      multiple: true
  - type: input
    id: fwversion
    attributes:
      label: Your firmware version
      description: |
        Please use the latest released firmware and check if the bug still occurs.
        If it occurs only in "Cutting Edge build" please mention this.
        Bangle 2: [firmware update instructions](https://www.espruino.com/Bangle.js2#firmware-updates)
        Bangle 2: [firmware update instructions](https://www.espruino.com/Bangle.js#firmware-updates)
      placeholder: e.g. 2v11
    validations:
      required: true
  - type: textarea
    id: report
    attributes:
      label: Bug description
      description: Please also mention the expected behaviour.
      placeholder: |
        **Describe the bug**
        A clear and concise description of what the bug is.
        
        **Expected behavior**
        A clear and concise description of what you expected to happen.

        **Steps to reproduce
        1. Start app xy
        2. choose abc
        3. bug occurs

        It could be helpfull for us to provide
    validations:
      required: true