name: Bangle Bug report
description: Bangle: Create a report to help us improve!
title: "[Bug]: "
#title: "[general/app/widget/clock e.g. clock] [development object e.g. antonclock] title"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### If you have a question then 
        ### ** Ask it in the [forum](http://forum.espruino.com/microcosms/1424/), please! **
  - type: checkboxes
    id: searched
    attributes:
      label: agree searched
      description: 
      options:
        label: I confirm that I have searched the forum and also for similiar bugs.
        required: true
  - type: checkboxes
    id: bangle
    attributes:
      label: hwversion
      description: Which Bangle hw version is affected?
      options:
        - Bangle 1
        - Bangle 2
  - type: textarea
    id: report
    attributes:
      label: Bug description
      description: and please mention expected behaviour
      placeholder: |
        **Describe the bug**
        A clear and concise description of what the bug is.
        
        **Expected behavior**
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: log_screens
    attributes:
      label: Log file or log outp or screenshots
      placeholder: |
        logfile, logoutout or screen
  - type: textarea
    id: addional
    attributes:
      label: Additional context
      description: for further helpfull information
      placeholder: |
        for further helpfull information