name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        working-directory: ./typescript
        run: npm ci
      - name: build types
        working-directory: ./typescript
        run: npm run build:types
      - name: build all TS apps
        working-directory: ./typescript
        run: npm run build:apps
